/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#e5e3ff",
        "tertiary-fixed-dim": "#c0c1ff",
        "on-primary": "#3f008e",
        "primary": "#d2bbff",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#5a00c6",
        "error-container": "#93000a",
        "on-secondary-container": "#5b3800",
        "on-primary-fixed": "#25005a",
        "tertiary": "#c0c1ff",
        "on-surface": "#e2e2e2",
        "surface": "#131313",
        "secondary-container": "#ee9800",
        "on-primary-container": "#ede0ff",
        "outline": "#958da1",
        "tertiary-container": "#5254df",
        "outline-variant": "#4a4455",
        "surface-container": "#1f1f1f",
        "on-secondary-fixed-variant": "#653e00",
        "background": "#131313",
        "on-secondary-fixed": "#2a1700",
        "surface-container-high": "#2a2a2a",
        "primary-container": "#7c3aed",
        "on-tertiary": "#1000a9",
        "error": "#ffb4ab",
        "inverse-surface": "#e2e2e2",
        "surface-bright": "#393939",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#1b1b1b",
        "primary-fixed": "#eaddff",
        "secondary": "#ffb95f",
        "surface-container-lowest": "#0e0e0e",
        "tertiary-fixed": "#e1e0ff",
        "on-tertiary-fixed": "#07006c",
        "secondary-fixed-dim": "#ffb95f",
        "inverse-primary": "#732ee4",
        "surface-tint": "#d2bbff",
        "surface-variant": "#353535",
        "inverse-on-surface": "#303030",
        "on-background": "#e2e2e2",
        "primary-fixed-dim": "#d2bbff",
        "on-secondary": "#472a00",
        "secondary-fixed": "#ffddb8",
        "on-surface-variant": "#ccc3d8",
        "surface-dim": "#131313",
        "surface-container-highest": "#353535",
        "on-tertiary-fixed-variant": "#2f2ebe"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
    },
  },
  plugins: [],
};
